### ISSUE TITLE
First Online Meeting

### ISSUE THREAD

**Issue by aspasia** [aspasia/clojurebridge-amsterdam#1]
## Proposed agenda
- [x] More diverse crowd than women - change the message? consult ClojuBridge?
- [ ] Laptops/ Install fest
- [x] Pick a date for the first session
- [x] Promoting event
- [x] Curriculum preparation
- [x] Teaching preparation
- [ ] Code of conduct
- [x] Test session
- [ ] Level of attendees (beginners?)
- [ ] Website
## Future topics
- [ ] Expand to more diverse crowd. Eg. Tackle more underprivileged "classes"
- [ ] More languages than english if there is demand (translate material)
- [ ] Mailing list with other ClojureBridge peers

**Comment by aspasia** [comment]
- Erwin
- [ ] Have a look at the curriculum for the test run http://clojurebridge.github.io/curriculum/#/1 https://github.com/ClojureBridge/curriculum
- Michiel
- [ ] Contact ClojureBridge people, prepare a more generic message 
- Carlo
- [ ] Ask designer for flyers
- [ ] Maybe contact http://www.meetup.com/girlcode/
- Aspasia
- [ ] Date picker test round
- [ ] Contact Ali King
- Aspasia, Erwin and Michiel are available to promote ClojureBridge at http://amsterdam2016.codemotionworld.com/

**Comment by skuro** [comment]
- everyone
- [ ] study the curriculum before the test event

**Comment by aspasia** [comment]
The first  test event took place
