### ISSUE TITLE
Tasks after call on 21-04-2016 

### ISSUE THREAD

**Issue by aspasia** [aspasia/clojurebridge-amsterdam#2]
### Erwin
- [x] Have a look at the curriculum  and let us know what we need to prepare for the test run http://clojurebridge.github.io/curriculum/#/1 https://github.com/ClojureBridge/curriculum
### Michiel
- [x] Contact ClojureBridge people, prepare a more generic message 
### Carlo
- [x] Ask designer for flyers
- [x] Maybe contact http://www.meetup.com/girlcode/
### Aspasia
- [x] Date picker test round
- [x] Contact Ali King
### Other
- Aspasia, Erwin and Michiel are available to promote ClojureBridge at http://amsterdam2016.codemotionworld.com/

**Comment by skuro** [comment]
The DCD designer agreed to contribute a few graphics pro-bono! \o/
We just need to give her our specific requests, I can work on that.

**Comment by aspasia** [comment]
Done!
